In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance
from matplotlib import pyplot as plt

In [ ]:
features=['Within office hour' ,'Duration from office start' ,
'Duration from office end' , 'Within office break hour' , 'Duration from office break start' , 'Duration from office break end' ,
'Elapsed time from last reported 0' , 'Elapsed time from last reported 1' , 'Did the user report?']

In [ ]:
#Valence
users=[12,13,14,15,16,17,18,19,20,23,25,26,29,32,33,36,37]
imp_all={}
for id in users:
  dataset = pd.read_csv('Tap/Valence/user_' + str(id) + '.csv')
  if len(dataset)==0:
    continue
  dataset.drop('Sample id', inplace=True, axis=1) #removing the sample id column
  dataset.replace('Yes',1,inplace=True)
  dataset.replace('No',0,inplace=True)
  X=dataset.iloc[:,:-1]
  y=dataset.iloc[:,-1:]
  print(X.head())
  print(y.head())
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

  rf = RandomForestClassifier(n_estimators=150)
  rf.fit(X_train, y_train)

  sort = rf.feature_importances_.argsort()
  j=0
  imp={}
  for item in rf.feature_importances_:
    imp[features[j]]=item
    j+=1
  imp_all[id]=imp
  print("id=",id)
  print(sort)

   Within office hour  Duration from office start  Duration from office end  \
0                   1                       415.0                   43615.0   
1                   1                       401.0                   43601.0   
2                   0                     33728.0                   76928.0   
3                   0                     33718.0                   76918.0   
4                   1                       488.0                   42712.0   

   Within office break hour  Duration from office break start  \
0                         0                             415.0   
1                         0                             401.0   
2                         0                           33728.0   
3                         0                           33718.0   
4                         1                             488.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         22015.0                           12

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 12
[0 3 1 2 4 5 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     18972.0                    8172.0   
1                   0                     20354.0                    9554.0   
2                   0                     35924.0                   25124.0   
3                   0                     40625.0                   51425.0   
4                   0                     17978.0                   28778.0   

   Within office break hour  Duration from office break start  \
0                         0                           18972.0   
1                         0                           20354.0   
2                         0                           35924.0   
3                         0                           40625.0   
4                         0                           17978.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         16572.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 13
[3 0 1 5 4 2 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                     18596.0                   49196.0   
1                   1                     18070.0                   48670.0   
2                   1                     22095.0                    8505.0   
3                   1                     22105.0                    8495.0   
4                   1                     17121.0                   47721.0   

   Within office break hour  Duration from office break start  \
0                         0                           18596.0   
1                         0                           18070.0   
2                         0                           22095.0   
3                         0                           22105.0   
4                         0                           17121.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         25796.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 14
[0 3 4 1 2 5 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     17814.0                   22014.0   
1                   0                     17440.0                   21640.0   
2                   1                      9742.0                   13942.0   
3                   1                      9728.0                   13928.0   
4                   1                      1923.0                    2277.0   

   Within office break hour  Duration from office break start  \
0                         0                           17814.0   
1                         0                           17440.0   
2                         0                            9742.0   
3                         0                            9728.0   
4                         0                            1923.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         18714.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 15
[3 0 4 1 5 2 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     21425.0                   50225.0   
1                   0                     20919.0                   49719.0   
2                   1                      1975.0                   26825.0   
3                   1                      2108.0                   26692.0   
4                   1                     14875.0                   13925.0   

   Within office break hour  Duration from office break start  \
0                         0                           21425.0   
1                         0                           20919.0   
2                         1                            1975.0   
3                         1                            2108.0   
4                         0                           14875.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         32225.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 16
[0 3 2 4 1 5 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     38757.0                   71157.0   
1                   0                     39939.0                   72339.0   
2                   0                      6330.0                   38730.0   
3                   0                      7145.0                   39545.0   
4                   0                     20992.0                   53392.0   

   Within office break hour  Duration from office break start  \
0                         0                           38757.0   
1                         0                           39939.0   
2                         0                            6330.0   
3                         0                            7145.0   
4                         0                           20992.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         36957.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 19
[0 3 2 5 4 6 1 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     67678.0                   53278.0   
1                   0                     67732.0                   53332.0   
2                   0                     77578.0                   63178.0   
3                   0                     77786.0                   63386.0   
4                   0                     28978.0                   14578.0   

   Within office break hour  Duration from office break start  \
0                         0                           67678.0   
1                         0                           67732.0   
2                         0                           77578.0   
3                         0                           77786.0   
4                         0                           28978.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         65878.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 20
[0 3 4 5 2 1 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                     19791.0                    9009.0   
1                   1                     20154.0                    8646.0   
2                   0                     30586.0                    1786.0   
3                   0                     30596.0                    1796.0   
4                   0                     40498.0                   69298.0   

   Within office break hour  Duration from office break start  \
0                         0                           19791.0   
1                         0                           20154.0   
2                         0                           30586.0   
3                         0                           30596.0   
4                         0                           40498.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          5391.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 23
[0 3 2 1 4 5 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     19801.0                    1801.0   
1                   0                     35270.0                   17270.0   
2                   0                     35341.0                   17341.0   
3                   0                     45312.0                   27312.0   
4                   0                     45499.0                   27499.0   

   Within office break hour  Duration from office break start  \
0                         0                           19801.0   
1                         0                           35270.0   
2                         0                           35341.0   
3                         0                           45312.0   
4                         0                           45499.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          1801.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 25
[0 3 5 2 1 4 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     20028.0                   20028.0   
1                   0                     22428.0                   22428.0   
2                   0                     53721.0                   53721.0   
3                   0                     53763.0                   53763.0   
4                   0                     80693.0                   80693.0   

   Within office break hour  Duration from office break start  \
0                         0                           20028.0   
1                         0                           22428.0   
2                         0                           53721.0   
3                         0                           53763.0   
4                         0                           80693.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         12828.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 26
[0 3 5 2 4 1 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                     19440.0                    9360.0   
1                   1                     19515.0                    9285.0   
2                   0                     45540.0                   16740.0   
3                   0                     45642.0                   16842.0   
4                   0                     56040.0                   27240.0   

   Within office break hour  Duration from office break start  \
0                         0                           19440.0   
1                         0                           19515.0   
2                         0                           45540.0   
3                         0                           45642.0   
4                         0                           56040.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         10440.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 29
[3 0 1 4 2 5 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     24021.0                    8721.0   
1                   0                     24038.0                    8738.0   
2                   0                     25348.0                   40648.0   
3                   0                     18801.0                   34101.0   
4                   1                      6785.0                   22085.0   

   Within office break hour  Duration from office break start  \
0                         0                           24021.0   
1                         0                           24038.0   
2                         0                           25348.0   
3                         0                           18801.0   
4                         0                            6785.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         22221.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 32
[3 0 4 5 6 2 1 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                      7139.0                   23339.0   
1                   1                      6944.0                   23144.0   
2                   0                     31861.0                   15661.0   
3                   0                     31873.0                   15673.0   
4                   1                      8641.0                   24841.0   

   Within office break hour  Duration from office break start  \
0                         0                            7139.0   
1                         0                            6944.0   
2                         0                           31861.0   
3                         0                           31873.0   
4                         0                            8641.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          8939.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 33
[3 0 5 4 2 1 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                      6042.0                   20442.0   
1                   1                      5729.0                   20129.0   
2                   1                     12864.0                    1536.0   
3                   1                     13375.0                    1025.0   
4                   0                     48133.0                   62533.0   

   Within office break hour  Duration from office break start  \
0                         0                            6042.0   
1                         0                            5729.0   
2                         0                           12864.0   
3                         0                           13375.0   
4                         0                           48133.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          7842.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 36
[3 0 4 1 5 2 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     17982.0                    1782.0   
1                   0                     17990.0                    1790.0   
2                   0                     26682.0                   10482.0   
3                   0                     26733.0                   10533.0   
4                   0                     35682.0                   19482.0   

   Within office break hour  Duration from office break start  \
0                         0                           17982.0   
1                         0                           17990.0   
2                         0                           26682.0   
3                         0                           26733.0   
4                         0                           35682.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         16182.0    

<ipython-input-12-b773c445cb78>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 37
[3 0 4 1 2 5 6 7]


In [ ]:
print(imp_all)

{12: {'Within office hour': 0.00449883062923137, 'Duration from office start': 0.1503857867473193, 'Duration from office end': 0.16023178964886775, 'Within office break hour': 0.006756534879014747, 'Duration from office break start': 0.16157661292516262, 'Duration from office break end': 0.165420217900453, 'Elapsed time from last reported 0': 0.16830782811212935, 'Elapsed time from last reported 1': 0.18282239915782192}, 13: {'Within office hour': 0.005348702023318873, 'Duration from office start': 0.15652127410461505, 'Duration from office end': 0.1631709725654007, 'Within office break hour': 0.0017694634512622027, 'Duration from office break start': 0.16248795575976407, 'Duration from office break end': 0.16040985920547174, 'Elapsed time from last reported 0': 0.1785717038474859, 'Elapsed time from last reported 1': 0.1717200690426815}, 14: {'Within office hour': 0.006163491518484786, 'Duration from office start': 0.1516804400959652, 'Duration from office end': 0.15461212345752173, '

In [ ]:
#Arousal
users=[12,13,14,15,16,17,18,19,20,23,25,26,29,32,33,36,37]
imp_all={}
for id in users:
  dataset = pd.read_csv('Tap/Arousal/user_' + str(id) + '.csv')
  if len(dataset)==0:
    continue
  dataset.drop('Sample id', inplace=True, axis=1) #removing the sample id column
  dataset.replace('Yes',1,inplace=True)
  dataset.replace('No',0,inplace=True)
  X=dataset.iloc[:,:-1]
  y=dataset.iloc[:,-1:]
  print(X.head())
  print(y.head())
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

  rf = RandomForestClassifier(n_estimators=150)
  rf.fit(X_train, y_train)

  sort = rf.feature_importances_.argsort()
  j=0
  imp={}
  for item in rf.feature_importances_:
    imp[features[j]]=item
    j+=1
  imp_all[id]=imp
  print("id=",id)
  print(sort)

   Within office hour  Duration from office start  Duration from office end  \
0                   1                      8923.0                   34277.0   
1                   1                      8941.0                   34259.0   
2                   1                      5226.0                   48426.0   
3                   1                      5174.0                   48374.0   
4                   1                     16732.0                   26468.0   

   Within office break hour  Duration from office break start  \
0                         1                            8923.0   
1                         1                            8941.0   
2                         0                            5226.0   
3                         0                            5174.0   
4                         1                           16732.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         12677.0                            6

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 12
[0 3 2 5 4 1 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                      6664.0                   17464.0   
1                   1                      6639.0                   17439.0   
2                   0                     22602.0                   11802.0   
3                   0                     23276.0                   12476.0   
4                   0                     32210.0                   21410.0   

   Within office break hour  Duration from office break start  \
0                         0                            6664.0   
1                         0                            6639.0   
2                         0                           22602.0   
3                         0                           23276.0   
4                         0                           32210.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          9064.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 13
[3 0 1 4 5 2 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                     17221.0                   47821.0   
1                   1                     14980.0                   45580.0   
2                   1                      3037.0                   27563.0   
3                   1                      9575.0                   21025.0   
4                   1                     26178.0                    4422.0   

   Within office break hour  Duration from office break start  \
0                         0                           17221.0   
1                         0                           14980.0   
2                         1                            3037.0   
3                         0                            9575.0   
4                         0                           26178.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         24421.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 14
[0 3 1 2 5 4 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     12793.0                    8593.0   
1                   0                     12863.0                    8663.0   
2                   0                     25290.0                   21090.0   
3                   0                     25577.0                   21377.0   
4                   0                     34059.0                   29859.0   

   Within office break hour  Duration from office break start  \
0                         0                           12793.0   
1                         0                           12863.0   
2                         0                           25290.0   
3                         0                           25577.0   
4                         0                           34059.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         11893.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 15
[3 0 4 1 2 5 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                      6777.0                   22023.0   
1                   1                      8652.0                   20148.0   
2                   1                     26577.0                    2223.0   
3                   1                     26750.0                    2050.0   
4                   1                     15477.0                   13323.0   

   Within office break hour  Duration from office break start  \
0                         1                            6777.0   
1                         1                            8652.0   
2                         0                           26577.0   
3                         0                           26750.0   
4                         0                           15477.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          4023.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 16
[3 0 2 1 5 4 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                     13983.0                   16617.0   
1                   1                     14256.0                   16344.0   
2                   1                     23845.0                    6755.0   
3                   1                     24062.0                    6538.0   
4                   0                     25652.0                   56252.0   

   Within office break hour  Duration from office break start  \
0                         0                           13983.0   
1                         0                           14256.0   
2                         0                           23845.0   
3                         0                           24062.0   
4                         0                           25652.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          4983.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 17
[0 3 4 1 5 2 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     29177.0                     377.0   
1                   0                     29240.0                     440.0   
2                   1                     17831.0                   10969.0   
3                   1                     18109.0                   10691.0   
4                   1                     15125.0                   13675.0   

   Within office break hour  Duration from office break start  \
0                         0                           29177.0   
1                         0                           29240.0   
2                         0                           17831.0   
3                         0                           18109.0   
4                         0                           15125.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         16577.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 18
[0 3 4 7 1 2 5 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                      2984.0                   35384.0   
1                   0                      2994.0                   35394.0   
2                   0                     46027.0                   78427.0   
3                   0                     47108.0                   79508.0   
4                   0                      3470.0                   35870.0   

   Within office break hour  Duration from office break start  \
0                         0                            2984.0   
1                         0                            2994.0   
2                         0                           46027.0   
3                         0                           47108.0   
4                         0                            3470.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          1184.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 19
[0 3 2 4 5 1 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     51069.0                   36669.0   
1                   0                     51351.0                   36951.0   
2                   0                     77500.0                   63100.0   
3                   0                     78026.0                   63626.0   
4                   0                     34268.0                   19868.0   

   Within office break hour  Duration from office break start  \
0                         0                           51069.0   
1                         0                           51351.0   
2                         0                           77500.0   
3                         0                           78026.0   
4                         0                           34268.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         49269.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 20
[0 3 4 5 1 2 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                      5121.0                   33921.0   
1                   1                      5026.0                   33826.0   
2                   1                     13812.0                   14988.0   
3                   1                     13819.0                   14981.0   
4                   1                     28251.0                     549.0   

   Within office break hour  Duration from office break start  \
0                         0                            5121.0   
1                         0                            5026.0   
2                         1                           13812.0   
3                         1                           13819.0   
4                         0                           28251.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         19521.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 23
[0 3 2 5 1 4 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     19844.0                    1844.0   
1                   0                     30980.0                   12980.0   
2                   0                     58606.0                   40606.0   
3                   0                     59008.0                   41008.0   
4                   0                     22821.0                   40821.0   

   Within office break hour  Duration from office break start  \
0                         0                           19844.0   
1                         0                           30980.0   
2                         0                           58606.0   
3                         0                           59008.0   
4                         0                           22821.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          1844.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 25
[0 3 5 2 4 1 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     54012.0                   54012.0   
1                   0                     54919.0                   54919.0   
2                   0                     54917.0                   54917.0   
3                   0                     54972.0                   54972.0   
4                   0                     74099.0                   74099.0   

   Within office break hour  Duration from office break start  \
0                         0                           54012.0   
1                         0                           54919.0   
2                         0                           54917.0   
3                         0                           54972.0   
4                         0                           74099.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         46812.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 26
[0 3 4 5 1 2 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   0                     62894.0                   34094.0   
1                   0                     62911.0                   34111.0   
2                   1                     23259.0                    5541.0   
3                   1                     23959.0                    4841.0   
4                   0                     37718.0                    8918.0   

   Within office break hour  Duration from office break start  \
0                         0                           62894.0   
1                         0                           62911.0   
2                         0                           23259.0   
3                         0                           23959.0   
4                         0                           37718.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         53894.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 29
[3 0 4 2 1 5 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                      7271.0                   22571.0   
1                   1                      7147.0                   22447.0   
2                   1                       881.0                   16181.0   
3                   1                       150.0                   15150.0   
4                   1                     11115.0                    4185.0   

   Within office break hour  Duration from office break start  \
0                         0                            7271.0   
1                         0                            7147.0   
2                         0                             881.0   
3                         1                             150.0   
4                         0                           11115.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          9071.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 32
[3 0 1 5 4 2 6 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                      8641.0                   24841.0   
1                   1                      8624.0                   24824.0   
2                   1                      4259.0                   11941.0   
3                   1                      4266.0                   11934.0   
4                   1                     14159.0                    2041.0   

   Within office break hour  Duration from office break start  \
0                         0                            8641.0   
1                         0                            8624.0   
2                         0                            4259.0   
3                         0                            4266.0   
4                         0                           14159.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         10441.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 33
[3 0 5 1 4 2 7 6]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                     13914.0                     486.0   
1                   1                     13976.0                     424.0   
2                   0                     29962.0                   15562.0   
3                   0                     30261.0                   15861.0   
4                   1                      5742.0                   20142.0   

   Within office break hour  Duration from office break start  \
0                         0                           13914.0   
1                         0                           13976.0   
2                         0                           29962.0   
3                         0                           30261.0   
4                         0                            5742.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                         12114.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 36
[3 0 4 5 1 6 2 7]
   Within office hour  Duration from office start  Duration from office end  \
0                   1                      5418.0                   21618.0   
1                   1                      4088.0                   20288.0   
2                   1                      9882.0                    6318.0   
3                   1                      9897.0                    6303.0   
4                   0                     17982.0                    1782.0   

   Within office break hour  Duration from office break start  \
0                         0                            5418.0   
1                         0                            4088.0   
2                         0                            9882.0   
3                         0                            9897.0   
4                         0                           17982.0   

   Duration from office break end  Elapsed time from last reported 0  \
0                          7218.0    

<ipython-input-15-ed54f1a7225c>:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


id= 37
[3 0 5 4 2 1 7 6]


In [ ]:
print(imp_all)

{12: {'Within office hour': 0.00444750906325178, 'Duration from office start': 0.1648436710807513, 'Duration from office end': 0.1539975395528264, 'Within office break hour': 0.0058902475687973195, 'Duration from office break start': 0.16005567251648914, 'Duration from office break end': 0.15785401263738638, 'Elapsed time from last reported 0': 0.17003032567845833, 'Elapsed time from last reported 1': 0.18288102190203936}, 13: {'Within office hour': 0.004610978812774903, 'Duration from office start': 0.15651524610579862, 'Duration from office end': 0.16432848398758831, 'Within office break hour': 0.0026657279256167986, 'Duration from office break start': 0.15901821559425022, 'Duration from office break end': 0.15985141094772665, 'Elapsed time from last reported 0': 0.17701599905422946, 'Elapsed time from last reported 1': 0.17599393757201515}, 14: {'Within office hour': 0.0027780942357009163, 'Duration from office start': 0.15437983128024546, 'Duration from office end': 0.1549034346758